In [25]:
# Libraries and dependencies
import pandas as pd
import scipy.stats as st
import numpy as np

In [28]:
# Pulling the csv
raw_data = pd.read_csv('03_data.csv', index_col=0)

raw_data

,precio_m2,superficie_total,categoria,dormitorios,baños,cocheras,colonia,alcaldia,dist_metro
0,60144.927536,138.0,departamento,2.0,3.0,2.0,POLANCO REFORMA (POLANCO),MIGUEL HIDALGO,499.558324
1,104651.162791,172.0,departamento,2.0,2.0,2.0,POLANCO REFORMA (POLANCO),MIGUEL HIDALGO,755.632370
2,85919.540230,174.0,departamento,2.0,2.0,2.0,POLANCO REFORMA (POLANCO),MIGUEL HIDALGO,772.890462
3,5092.622951,183.0,departamento,3.0,3.0,2.0,POLANCO REFORMA (POLANCO),MIGUEL HIDALGO,1004.848305
4,93125.000000,160.0,departamento,2.0,2.0,2.0,POLANCO REFORMA (POLANCO),MIGUEL HIDALGO,480.029999
...,...,...,...,...,...,...,...,...,...
6322,13824.324324,148.0,casa,3.0,2.0,1.0,VENUSTIANO CARRANZA,VENUSTIANO CARRANZA,727.209594
6323,26143.464052,306.0,casa,NaN,NaN,NaN,PENSADOR MEXICANO I,VENUSTIANO CARRANZA,290.130137
6324,2402.173913,276.0,casa,2.0,1.0,1.0,LOMAS DE LA ERA,ALVARO OBREGON,8566.632773
6325,46153.846154,143.0,casa,5.0,4.0,2.0,LOS GIRASOLES II,COYOACAN,2907.480929
6326,8240.740741,108.0,casa,3.0,4.0,1.0,MALACATES (AMPL),GUSTAVO A. MADERO,9289.681321

In [27]:
# Finding price outliers
quartiles = raw_data['precio_m2'].quantile([0.25, 0.5, 0.75])
lower_bound = quartiles[0.25] - (1.5 * (quartiles[0.75] - quartiles[0.25]))
upper_bound = quartiles[0.75] + (1.5 * (quartiles[0.75] - quartiles[0.25]))

# Classifying outliers
outliers = raw_data['price']